name: gen snake

on:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # ► SVG‑only variants (no Docker layer)
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/only-svg/github-contribution-grid-snake.svg
            dist/only-svg/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/only-svg/github-contribution-grid-snake-blue.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # ► Full renderer (SVG + optional GIF)
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/docker/github-contribution-grid-snake.svg
            dist/docker/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/docker/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # ► Quick sanity‑check to make sure all files were produced
      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-snake.svg
          test -f dist/only-svg/github-contribution-grid-snake-dark.svg
          test -f dist/only-svg/github-contribution-grid-snake-blue.svg
          test -f dist/docker/github-contribution-grid-snake.svg
          test -f dist/docker/github-contribution-grid-snake-dark.svg
          test -f dist/docker/github-contribution-grid-snake.gif

      # ► Push everything in /dist to a dedicated branch so the raw files are accessible
      - name: push github-contribution-grid-snake assets to the output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: manual-run-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
